spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\\PROJECTS\\JAVA\\dowczarek\\todo-app\\todo-db'
    driverClassName: org.h2.Driver
    username: sa
    password: password